<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Pages\Reports\**" />
	  <Content Remove="Pages\Reports\**" />
	  <EmbeddedResource Remove="Pages\Reports\**" />
	  <None Remove="Pages\Reports\**" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\css\fonts.css" />
	  <Content Remove="wwwroot\css\fonts\Montserrat-Italic-VariableFont_wght.ttf" />
	  <Content Remove="wwwroot\css\fonts\Montserrat-Regular.otf" />
	  <Content Remove="wwwroot\css\fonts\open-iconic.eot" />
	  <Content Remove="wwwroot\css\fonts\open-iconic.otf" />
	  <Content Remove="wwwroot\css\fonts\open-iconic.svg" />
	  <Content Remove="wwwroot\css\fonts\open-iconic.ttf" />
	  <Content Remove="wwwroot\css\fonts\open-iconic.woff" />
	  <Content Remove="wwwroot\css\sidebar.css" />
	  <Content Remove="wwwroot\css\theme.css" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="wwwroot\css\fonts.css" />
	  <EmbeddedResource Include="wwwroot\css\fonts\Montserrat-Italic-VariableFont_wght.ttf" />
	  <EmbeddedResource Include="wwwroot\css\fonts\Montserrat-Regular.otf" />
	  <EmbeddedResource Include="wwwroot\css\fonts\open-iconic.eot" />
	  <EmbeddedResource Include="wwwroot\css\fonts\open-iconic.otf" />
	  <EmbeddedResource Include="wwwroot\css\fonts\open-iconic.svg" />
	  <EmbeddedResource Include="wwwroot\css\fonts\open-iconic.ttf" />
	  <EmbeddedResource Include="wwwroot\css\fonts\open-iconic.woff" />
	  <EmbeddedResource Include="wwwroot\css\sidebar.css" />
	  <EmbeddedResource Include="wwwroot\css\theme.css" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\gad.aaportal.components\gad.aaportal.components.csproj" />
    <ProjectReference Include="..\gad.aaportal.consumers\gad.aaportal.consumers.csproj" />
  </ItemGroup>

</Project>

