using System;
using System.Collections.Generic;

namespace gad.aaportal.models.Entity.Dbo
{
    public partial class RepCartera
    {
        public int IdCartera { get; set; }
        public int? CodigoTitulo { get; set; }
        public int? CodigoDescripcion { get; set; }
        public double? ValorCartera { get; set; }
        public double? EmisionEnero { get; set; }
        public double? RecaudacionCartEnero { get; set; }
        public double? RecaudacionCorrEnero { get; set; }
        public double? BajasCartEnero { get; set; }
        public double? BajasCorrEnero { get; set; }
        public double? SaldoCartEnero { get; set; }
        public double? SaldoCorrEnero { get; set; }
        public double? SaldoTotalEnero { get; set; }
        public double? EmisionFeb { get; set; }
        public double? RecaudacionCartFeb { get; set; }
        public double? RecaudacionCorrFeb { get; set; }
        public double? BajasCartFeb { get; set; }
        public double? BajasCorrFeb { get; set; }
        public double? SaldoCartFeb { get; set; }
        public double? SaldoCorrFeb { get; set; }
        public double? SaldoTotalFeb { get; set; }
        public double? EmisionMarzo { get; set; }
        public double? RecaudacionCartMarzo { get; set; }
        public double? RecaudacionCorrMarzo { get; set; }
        public double? BajasCartMarzo { get; set; }
        public double? BajasCorrMarzo { get; set; }
        public double? SaldoCartMarzo { get; set; }
        public double? SaldoCorrMarzo { get; set; }
        public double? SaldoTotalMarzo { get; set; }
        public double? EmisionAbril { get; set; }
        public double? RecaudacionCartAbril { get; set; }
        public double? RecaudacionCorrAbril { get; set; }
        public double? BajasCartAbril { get; set; }
        public double? BajasCorrAbril { get; set; }
        public double? SaldoCartAbril { get; set; }
        public double? SaldoCorrAbril { get; set; }
        public double? SaldoTotalAbril { get; set; }
        public double? EmisionMayo { get; set; }
        public double? RecaudacionCartMayo { get; set; }
        public double? RecaudacionCorrMayo { get; set; }
        public double? BajasCartMayo { get; set; }
        public double? BajasCorrMayo { get; set; }
        public double? SaldoCartMayo { get; set; }
        public double? SaldoCorrMayo { get; set; }
        public double? SaldoTotalMayo { get; set; }
        public double? EmisionJun { get; set; }
        public double? RecaudacionCartJun { get; set; }
        public double? RecaudacionCorrJun { get; set; }
        public double? BajasCartJun { get; set; }
        public double? BajasCorrJun { get; set; }
        public double? SaldoCartJun { get; set; }
        public double? SaldoCorrJun { get; set; }
        public double? SaldoTotalJun { get; set; }
        public double? EmisionJul { get; set; }
        public double? RecaudacionCartJul { get; set; }
        public double? RecaudacionCorrJul { get; set; }
        public double? BajasCartJul { get; set; }
        public double? BajasCorrJul { get; set; }
        public double? SaldoCartJul { get; set; }
        public double? SaldoCorrJul { get; set; }
        public double? SaldoTotalJul { get; set; }
        public double? EmisionAg { get; set; }
        public double? RecaudacionCartAg { get; set; }
        public double? RecaudacionCorrAg { get; set; }
        public double? BajasCartAg { get; set; }
        public double? BajasCorrAg { get; set; }
        public double? SaldoCartAg { get; set; }
        public double? SaldoCorrAg { get; set; }
        public double? SaldoTotalAg { get; set; }
        public double? EmisionSep { get; set; }
        public double? RecaudacionCartSep { get; set; }
        public double? RecaudacionCorrSep { get; set; }
        public double? BajasCartSep { get; set; }
        public double? BajasCorrSep { get; set; }
        public double? SaldoCartSep { get; set; }
        public double? SaldoCorrSep { get; set; }
        public double? SaldoTotalSep { get; set; }
        public double? EmisionOct { get; set; }
        public double? RecaudacionCartOct { get; set; }
        public double? RecaudacionCorrOct { get; set; }
        public double? BajasCartOct { get; set; }
        public double? BajasCorrOct { get; set; }
        public double? SaldoCartOct { get; set; }
        public double? SaldoCorrOct { get; set; }
        public double? SaldoTotalOct { get; set; }
        public double? EmisionNov { get; set; }
        public double? RecaudacionCartNov { get; set; }
        public double? RecaudacionCorrNov { get; set; }
        public double? BajasCartNov { get; set; }
        public double? BajasCorrNov { get; set; }
        public double? SaldoCartNov { get; set; }
        public double? SaldoCorrNov { get; set; }
        public double? SaldoTotalNov { get; set; }
        public double? EmisionDic { get; set; }
        public double? RecaudacionCartDic { get; set; }
        public double? RecaudacionCorrDic { get; set; }
        public double? BajasCartDic { get; set; }
        public double? BajasCorrDic { get; set; }
        public double? SaldoCartDic { get; set; }
        public double? SaldoCorrDic { get; set; }
        public double? SaldoTotalDic { get; set; }
        public int? Anio { get; set; }
    }
}
